from pygame.locals import USEREVENT

PLAYERFIRE = USEREVENT + 1
REACHEDBORDER = USEREVENT + 2

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500

PLAYER_OFFSET = 25
BALL_OFFSET = PLAYER_OFFSET + 10

RADIUS = 6
START_VEL = [5, 5]

FONT_SIZE = 40
SCORE_OFFSETS = [200, 100]