from pygame.locals import USEREVENT

PLAYER_FIRE_EVENT = USEREVENT + 1
REACHED_BORDER_EVENT = USEREVENT + 2

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500

PLAYER_OFFSET = 25
BALL_OFFSET = PLAYER_OFFSET + 13

BALL_RADIUS = 8
BALL_VEL = [7, 7]
BALL_PIXELS = 2

FONT_SIZE = 40
SCORE_OFFSETS = [200, 100]

SFX_VOLUME = 0.4

LINE_WIDTH = 6
LINE_HEIGHT = 40
LINE_GAP = 20
LINE_OFFSET = 10